<?php

/**
 * @file
 * Install, update and uninstall functions for the Shunt module.
 */

/**
 * Implements hook_uninstall().
 */
function shunt_uninstall() {
  // Delete ALL shunt status persistent variables.
  drupal_load('module', 'shunt');
  db_delete('variable')
    ->condition('name', db_like(SHUNT_VARIABLE_PREFIX) . '%', 'LIKE')
    ->execute();
  cache_clear_all('variables', 'cache_bootstrap');
}
