<?php

/**
 * @file
 * Provides "shunts" that enable your site to fail gracefully under strain.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function shunt_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'shunt.list':
      return '<p>' . t('Enable (or "trip") shunts to cause the functionality that depends on them to fail gracefully.') . '</p>';
  }
}
