<?php

/**
 * @file
 * Provides "shunts" that enable your site to fail gracefully under strain.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function shunt_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'shunt.list':
      return '<p>' . t('Trip shunts to cause dependant functionality to fail gracefully. Reset them to restore normal functionality.') . '</p>';
  }
}
