<?php

/**
 * @file
 * An API and UI for defining and interacting with "shunts".
 *
 * Enable your site to fail gracefully under strain.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function shunt_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'shunt.config':
      return '<p>' . t('Enable (or "trip") shunts by checking their checkboxes below to cause the functionality that depends on them to fail gracefully.') . '</p>';
  }
}