<?php

/**
 * @file
 * An example implementation of of Shunt module.
 */

/**
 * Implements hook_theme().
 */
function shuntexample_theme($existing, $type, $theme, $path) {
  return array(
    'shuntexample_fail' => array(
      'render element' => 'content',
      'template' => 'shuntexample-fail',
    ),
    'shuntexample_hello' => array(
      'render element' => 'content',
      'template' => 'shuntexample-hello',
    ),
  );
}
