<?php

/**
 * @file
 * An example implementation of of Shunt module.
 */

/**
 * Implements hook_theme().
 */
function shuntexample_theme($existing, $type, $theme, $path) {
  return [
    'shuntexample_fail' => [
      'render element' => 'content',
      'template' => 'shuntexample-fail',
    ],
    'shuntexample_hello' => [
      'render element' => 'content',
      'template' => 'shuntexample-hello',
    ],
  ];
}
